previewsEnabled: true
services:
  - type: web
    name: api
    env: docker
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: ./
    region: frankfurt
    repo: https://github.com/Badminton-Apps/badman.git
    plan: starter
    pullRequestPreviewsEnabled: false
    branch: main
    buildFilter:
      paths:
        - apps/api/**
        - libs/backend/**
    autoDeploy: true
    envVars:
      - fromGroup: server
      - fromGroup: GLOBAL
      - fromGroup: cache

  - type: worker
    name: worker-sync
    env: docker
    dockerfilePath: ./apps/worker/sync/Dockerfile
    dockerContext: ./
    region: frankfurt
    repo: https://github.com/Badminton-Apps/badman.git
    pullRequestPreviewsEnabled: false
    plan: standard
    branch: main
    buildFilter:
      paths:
        - apps/worker/sync/**
        - libs/backend/**
    autoDeploy: true
    envVars:
      - fromGroup: server
      - fromGroup: GLOBAL
      - fromGroup: cache

  # next
  - type: web
    name: api-next
    env: docker
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: ./
    scaling: false
    region: frankfurt
    repo: https://github.com/Badminton-Apps/badman.git
    pullRequestPreviewsEnabled: true
    plan: free
    branch: develop
    buildFilter:
      paths:
        - apps/api/**
        - libs/backend/**
    autoDeploy: true
    envVars:
      - fromGroup: server-next
      - fromGroup: GLOBAL
      - fromGroup: cache

  - type: worker
    name: worker-sync-next
    env: docker
    dockerfilePath: ./apps/worker/sync/Dockerfile
    dockerContext: ./
    region: frankfurt
    repo: https://github.com/Badminton-Apps/badman.git
    pullRequestPreviewsEnabled: false
    branch: develop
    buildFilter:
      paths:
        - apps/worker/sync/**
        - libs/backend/**
    autoDeploy: true
    envVars:
      - fromGroup: server-next
      - fromGroup: GLOBAL
      - fromGroup: cache

  # Services
  - type: redis
    name: badman
    plan: starter
    region: frankfurt
    ipAllowList: [] # only allow internal connections
    maxmemoryPolicy: allkeys-lru

databases:
  - name: badman
    region: frankfurt
    plan: standard
    databaseName: badman
    user: badman
    ipAllowList: []
